package com.optel.dc.ext.qx.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.optel.dc.ext.qx.service.impl.QxSendResult;
import com.optel.qx.cci.codec.MsgHead;
import com.optel.qx.cci.payload.QxPayloadCodec;
import com.optel.qxinspection.qx.error.QxErrorCode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationEventPublisher;

import java.nio.ByteBuffer;

/**
 * Common base class for all auto-generated Qx protocol services.
 *
 * <p>Provides encoding/decoding, sending, and COMM log recording capabilities.
 * Subclasses are generated by the codec plugin based on YAML namespaces,
 * one implementation class per namespace.</p>
 *
 * <p>COMM logs automatically record each device communication, including:</p>
 * <ul>
 *   <li>Module name (namespace) -- extracted automatically from codecRegistry</li>
 *   <li>Operation description (operation) -- passed in by subclass from YAML schema</li>
 *   <li>Two pairs of messages: raw binary (hex) + converted Bean (JSON)</li>
 *   <li>Two timestamps: send time + receive time</li>
 * </ul>
 */
public abstract class AbstractGeneratedQxService extends AbstractQxService {

    protected final Logger log = LoggerFactory.getLogger(getClass());

    private final IQxDeviceService qxDeviceService;
    private final ApplicationEventPublisher eventPublisher;
    /**
     * Thread-safe, shared across all generated service instances,
     * avoids creating one per namespace.
     */
    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    protected AbstractGeneratedQxService(IQxDeviceService qxDeviceService,
                                         ApplicationEventPublisher eventPublisher) {
        this.qxDeviceService = qxDeviceService;
        this.eventPublisher = eventPublisher;
    }

    // ---- Encode / Send / Decode base methods ----

    @SuppressWarnings("unchecked")
    protected final <T> byte[] encode(T data) {
        return codecRegistry.getByType(
                (Class<T>) data.getClass()).encode(data);
    }

    /**
     * Send empty payload, judge success/failure by message header result field.
     * Used for commands without a request body.
     */
    protected final void sendAndCheck(String neId, int cmdCode, String operation) {
        long sendTs = System.currentTimeMillis();
        QxSendResult result = qxDeviceService.send(neId, cmdCode, new byte[0], null);
        long recvTs = System.currentTimeMillis();
        int ms = (int) (recvTs - sendTs);

        if (!result.isSuccess()) {
            sendFailAndThrow(neId, cmdCode, operation, sendTs, ms,
                    null, null, result);
        }

        logComm(neId, cmdCode, operation, true, sendTs, ms,
                null, null, toHex(result.getRawPayload()), null,
                "{\"deviceResult\":0}", result.getResponseHeader());
    }

    /**
     * Encode -> send -> judge success/failure by message header result field.
     *
     * <p>In the QX protocol, Set command success/failure is determined by the result
     * field in the24B message header (offset22, Word, 0=success). The judgment is
     * already done inside {@code QxDeviceServiceImpl.send}. Protocol specifies that
     * success responses only contain the header with no body, so the response body
     * is not read here.</p>
     */
    protected final <T> void sendAndCheck(String neId, int cmdCode, T data, String operation) {
        byte[] payload;
        try {
            payload = encode(data);
        } catch (Exception e) {
            logComm(neId, cmdCode, operation, false, 0L, 0,
                    null, toJson(data), null, null,
                    "{\"errorType\":\"ENCODE\",\"error\":\"" + escapeJson(e.getMessage()) + "\"}",
                    null);
            throw e;
        }

        long sendTs = System.currentTimeMillis();
        QxSendResult result = qxDeviceService.send(neId, cmdCode, payload, null);
        long recvTs = System.currentTimeMillis();
        int ms = (int) (recvTs - sendTs);

        if (!result.isSuccess()) {
            sendFailAndThrow(neId, cmdCode, operation, sendTs, ms,
                    toHex(payload), toJson(data), result);
        }

        logComm(neId, cmdCode, operation, true, sendTs, ms,
                toHex(payload), toJson(data), toHex(result.getRawPayload()), null,
                "{\"deviceResult\":0}", result.getResponseHeader());
    }

    /**
     * Set failure (transport layer error, or message header result != 0 already converted
     * to failure by send) -> record COMM log and throw exception.
     * If the device attaches a unified error body (section 2.2 case 3), decode the error
     * port details into the exception message.
     */
    private void sendFailAndThrow(String neId, int cmdCode, String operation,
                                  long sendTs, int ms,
                                  String reqHex, String reqBean, QxSendResult result) {
        int deviceCode = result.getDeviceErrorCode() != null
                ? result.getDeviceErrorCode() : QxErrorCode.OTHER_ERROR;
        String deviceMsg = result.getDeviceErrorMessage();
        String itemDetail = decodeSetErrorDetail(result.getRawPayload());
        log.error("{} failed: neId={}, cmdCode=0x{}, deviceResult={}, desc={}, itemDetail={}",
                operation, neId, String.format("%04X", cmdCode & 0xFFFF), deviceCode, deviceMsg,
                itemDetail);
        String summary = "{\"errorType\":\"SEND\",\"deviceResult\":" + deviceCode
                + ",\"error\":\"" + escapeJson(deviceMsg) + "\""
                + (itemDetail != null ? ",\"itemDetail\":\"" + escapeJson(itemDetail) + "\"" : "")
                + "}";
        logComm(neId, cmdCode, operation, false, sendTs, ms,
                reqHex, reqBean, toHex(result.getRawPayload()), null, summary,
                result.getResponseHeader());
        String msg = operation + " failed: [" + deviceCode + "] " + deviceMsg;
        throw new QxCommandException(deviceCode,
                itemDetail != null ? msg + " — " + itemDetail : msg);
    }

    /**
     * Decode the unified error body for a failed Set command (section 2.2 case 3:
     * header result != 0 with body).
     *
     * <p>Layout follows the old EMS OptSdhMem.xml definition {@code Optel_Set_Result}
     * (12 bytes): bSubCaseNo / bSlotID / bPortType / bPortSubType / wPortID /
     * wTSOrderID / wTSAttribute / result(Word).</p>
     *
     * @return detailed description of the error location; returns null if no body or
     *         insufficient length (e.g. section 2.2 case 2 header-only error)
     */
    private static String decodeSetErrorDetail(byte[] raw) {
        if (raw == null || raw.length < 12) {
            return null;
        }
        ByteBuffer buf = ByteBuffer.wrap(raw);
        int subcaseNo = buf.get() & 0xFF;
        int slotId = buf.get() & 0xFF;
        int portType = buf.get() & 0xFF;
        int portSubType = buf.get() & 0xFF;
        int portId = buf.getShort() & 0xFFFF;
        int tsOrderId = buf.getShort() & 0xFFFF;
        int tsAttribute = buf.getShort() & 0xFFFF;
        int itemResult = buf.getShort() & 0xFFFF;
        return "subcase=" + subcaseNo + " slot=" + slotId
                + " portType=0x" + String.format("%02X", portType)
                + " portSubType=0x" + String.format("%02X", portSubType)
                + " portId=" + portId + " tsOrderId=" + tsOrderId
                + " tsAttr=" + tsAttribute
                + " itemResult=" + itemResult + "(" + QxErrorCode.describe(itemResult) + ")";
    }

    /**
     * Encode -> send -> decode response via type-indexed codec.
     * Used for Get/list type commands where the response is not a simple result int.
     */
    protected final <Req, Resp> Resp sendAndDecode(String neId, int cmdCode, Req req,
                                                   Class<Resp> responseType, String operation) {
        byte[] payload;
        try {
            payload = encode(req);
        } catch (Exception e) {
            logComm(neId, cmdCode, operation, false, 0L, 0,
                    null, toJson(req), null, null,
                    "{\"errorType\":\"ENCODE\",\"error\":\"" + escapeJson(e.getMessage()) + "\"}",
                    null);
            throw e;
        }

        QxPayloadCodec<Resp> codec;
        try {
            codec = getCodec(responseType, cmdCode, neId);
        } catch (Exception e) {
            logComm(neId, cmdCode, operation, false, 0L, 0,
                    toHex(payload), toJson(req), null, null,
                    "{\"errorType\":\"CODEC_LOOKUP\",\"error\":\"" + escapeJson(e.getMessage()) + "\"}",
                    null);
            throw e;
        }

        long sendTs = System.currentTimeMillis();
        QxSendResult result = qxDeviceService.send(neId, cmdCode, payload, null);
        long recvTs = System.currentTimeMillis();
        int ms = (int) (recvTs - sendTs);

        if (!result.isSuccess()) {
            int deviceCode = result.getDeviceErrorCode() != null
                    ? result.getDeviceErrorCode() : QxErrorCode.OTHER_ERROR;
            String deviceMsg = result.getDeviceErrorMessage();
            log.error("{} failed: neId={}, cmdCode=0x{}, deviceResult={}, desc={}",
                    operation, neId, String.format("%04X", cmdCode & 0xFFFF), deviceCode, deviceMsg);
            logComm(neId, cmdCode, operation, false, sendTs, ms,
                    toHex(payload), toJson(req), null, null,
                    "{\"errorType\":\"SEND\",\"deviceResult\":" + deviceCode
                            + ",\"error\":\"" + escapeJson(deviceMsg) + "\"}",
                    result.getResponseHeader());
            throw new QxCommandException(deviceCode,
                    operation + " failed: [" + deviceCode + "] " + deviceMsg);
        }
        byte[] raw = result.getRawPayload();

        Resp decoded;
        try {
            decoded = codec.decode(raw);
        } catch (Exception e) {
            logComm(neId, cmdCode, operation, false, sendTs, ms,
                    toHex(payload), toJson(req), toHex(raw), null,
                    "{\"errorType\":\"DECODE\",\"error\":\"" + escapeJson(e.getMessage()) + "\"}",
                    result.getResponseHeader());
            throw e;
        }

        logComm(neId, cmdCode, operation, true, sendTs, ms,
                toHex(payload), toJson(req), toHex(raw), toJson(decoded), null,
                result.getResponseHeader());
        return decoded;
    }

    /**
     * Send empty payload -> decode response via type-indexed codec.
     * Used for Get commands without a request body.
     */
    protected final <Resp> Resp sendAndDecode(String neId, int cmdCode,
                                              Class<Resp> responseType, String operation) {
        QxPayloadCodec<Resp> codec;
        try {
            codec = getCodec(responseType, cmdCode, neId);
        } catch (Exception e) {
            logComm(neId, cmdCode, operation, false, 0L, 0,
                    null, null, null, null,
                    "{\"errorType\":\"CODEC_LOOKUP\",\"error\":\"" + escapeJson(e.getMessage()) + "\"}",
                    null);
            throw e;
        }

        long sendTs = System.currentTimeMillis();
        QxSendResult result = qxDeviceService.send(neId, cmdCode, new byte[0], null);
        long recvTs = System.currentTimeMillis();
        int ms = (int) (recvTs - sendTs);

        if (!result.isSuccess()) {
            int deviceCode = result.getDeviceErrorCode() != null
                    ? result.getDeviceErrorCode() : QxErrorCode.OTHER_ERROR;
            String deviceMsg = result.getDeviceErrorMessage();
            log.error("{} failed: neId={}, cmdCode=0x{}, deviceResult={}, desc={}",
                    operation, neId, String.format("%04X", cmdCode & 0xFFFF), deviceCode, deviceMsg);
            logComm(neId, cmdCode, operation, false, sendTs, ms,
                    null, null, null, null,
                    "{\"errorType\":\"SEND\",\"deviceResult\":" + deviceCode
                            + ",\"error\":\"" + escapeJson(deviceMsg) + "\"}",
                    result.getResponseHeader());
            throw new QxCommandException(deviceCode,
                    operation + " failed: [" + deviceCode + "] " + deviceMsg);
        }
        byte[] raw = result.getRawPayload();

        Resp decoded;
        try {
            decoded = codec.decode(raw);
        } catch (Exception e) {
            logComm(neId, cmdCode, operation, false, sendTs, ms,
                    null, null, toHex(raw), null,
                    "{\"errorType\":\"DECODE\",\"error\":\"" + escapeJson(e.getMessage()) + "\"}",
                    result.getResponseHeader());
            throw e;
        }

        logComm(neId, cmdCode, operation, true, sendTs, ms,
                null, null, toHex(raw), toJson(decoded), null,
                result.getResponseHeader());
        return decoded;
    }

    // ---- Log publishing ----

    /**
     * COMM log via SLF4J. When DeviceLogEvent / CommLogEntry infrastructure is available,
     * this can be upgraded to publish events via ApplicationEventPublisher.
     */
    private void logComm(String neId, int cmdCode, String operation,
                         boolean ok, long sendTs, int ms,
                         String reqHex, String reqBean,
                         String rspHex, String rspBean, String summary,
                         byte[] responseHeader) {
        try {
            String cmd = String.format("0x%04X", cmdCode & 0xFFFF);
            String namespace = resolveNamespace(cmdCode);
            String annotatedHeader = formatAnnotated("RSP HDR: ", responseHeader);
            if (log.isDebugEnabled()) {
                log.debug("COMM {} {} neId={} ns={} {}ms {} | req={} | rsp={} | {}",
                        ok ? "OK" : "FAIL", operation, neId, namespace, ms, cmd,
                        reqBean != null ? reqBean : reqHex,
                        rspBean != null ? rspBean : rspHex,
                        summary != null ? summary : "");
                if (annotatedHeader != null) {
                    log.debug("{}", annotatedHeader);
                }
            }
        } catch (Exception e) {
            log.debug("Failed to log COMM: neId={}", neId, e);
        }
    }

    // ---- Utility methods ----

    /**
     * Format a24-byte message header into annotated lines for COMM logs.
     * Returns null if header is null or too short.
     */
    static String formatAnnotated(String prefix, byte[] header) {
        if (header == null || header.length < MsgHead.HEAD_BYTE_LEN) {
            return null;
        }
        try {
            MsgHead h = MsgHead.wrap(header);
            String[] names   = {"msgLen", "ver", "opts", "reserve", "seqNum", "target", "source", "cmdCode", "result"};
            int[]    byteLen = {4, 1, 1, 2, 4, 4, 4, 2, 2};

            String[] decoded = {
                    String.valueOf(h.getMsgLen()),
                    String.valueOf(h.getVersion() & 0xFF),
                    h.needsResponse() ? "needRsp" : "noRsp",
                    "seg=" + ((h.getReserve() >> 8) & 0xFF) + "/" + (h.getReserve() & 0xFF),
                    h.getSeqNum() == 0 ? "trap" : (h.getSeqNum() == 0xFFFFFFFF ? "broadcast" : String.valueOf(h.getSeqNum())),
                    String.format("0x%08X", h.getTarget()),
                    String.format("0x%08X", h.getSource()),
                    String.format("0x%04X", h.getCmdCode() & 0xFFFF),
                    decodeResult(h.getResult())
            };

            int[] widths = new int[names.length];
            for (int i = 0; i < names.length; i++) {
                widths[i] = Math.max(Math.max(names[i].length(), byteLen[i] * 3 - 1), decoded[i].length());
            }

            int prefixLen = prefix.length();
            StringBuilder line1 = new StringBuilder(prefix);
            StringBuilder line2 = new StringBuilder(" ".repeat(prefixLen));
            int offset = 0;
            for (int i = 0; i < names.length; i++) {
                line1.append("| ").append(pad(names[i], widths[i])).append(' ');
                line2.append("| ").append(pad(hexBytes(header, offset, byteLen[i]), widths[i])).append(' ');
                offset += byteLen[i];
            }
            line1.append('|');
            line2.append('|');

            StringBuilder line3 = new StringBuilder(" ".repeat(prefixLen));
            for (int i = 0; i < names.length; i++) {
                line3.append("| ").append(pad(decoded[i], widths[i])).append(' ');
            }
            line3.append('|');

            return line1 + "\n" + line2 + "\n" + line3;
        } catch (Exception e) {
            return null;
        }
    }

    private static String decodeResult(short result) {
        int r = result & 0xFFFF;
        if (r == 0) return "OK";
        return String.format("0x%04X(%s)", r, QxErrorCode.describe(r));
    }

    private static String hexBytes(byte[] data, int offset, int len) {
        StringBuilder sb = new StringBuilder(len * 3);
        for (int i = 0; i < len; i++) {
            if (i > 0) sb.append(' ');
            sb.append(String.format("%02X", data[offset + i] & 0xFF));
        }
        return sb.toString();
    }

    private static String pad(String s, int width) {
        if (s.length() >= width) return s;
        return s + " ".repeat(width - s.length());
    }

    /**
     * Convert byte array to hex string (e.g. "01 02 03 FF").
     */
    static String toHex(byte[] bytes) {
        if (bytes == null || bytes.length == 0) return null;
        StringBuilder sb = new StringBuilder(bytes.length * 3);
        for (int i = 0; i < bytes.length; i++) {
            if (i > 0) sb.append(' ');
            sb.append(String.format("%02X", bytes[i] & 0xFF));
        }
        return sb.toString();
    }

    /**
     * Convert object to JSON string, returns null on exception.
     */
    static String toJson(Object obj) {
        if (obj == null) return null;
        try {
            return OBJECT_MAPPER.writeValueAsString(obj);
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * JSON string escaping.
     */
    static String escapeJson(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"")
                .replace("\n", "\\n").replace("\r", "\\r");
    }

    private String resolveNamespace(int cmdCode) {
        try {
            QxPayloadCodec<?> codec = codecRegistry.get((short) cmdCode);
            return codec != null ? codec.namespace() : null;
        } catch (Exception e) {
            return null;
        }
    }

    @SuppressWarnings("unchecked")
    private <Resp> QxPayloadCodec<Resp> getCodec(Class<Resp> responseType, int cmdCode, String neId) {
        QxPayloadCodec<Resp> codec =
                codecRegistry.getByType(responseType);
        if (codec == null) {
            log.error("No codec registered for response type: {} (neId={}, cmdCode=0x{})",
                    responseType.getName(), neId, String.format("%04X", cmdCode & 0xFFFF));
            throw new QxCommandException(QxErrorCode.OTHER_ERROR,
                    "No codec registered for response type: " + responseType.getName());
        }
        return codec;
    }
}
